public enum itemID
{
     none = 0,
     alcoolprothese = 20,
     cartoninconnu = 21,
     chrysentheme = 22,
     colisbabiole = 2,
     colisterre = 17,
     commandefleur = 4,
     demandechrys = 23,
     football = 19,
     geneatree = 13,
     lettrecomptable = 24,
     lettreconcert = 25,
     lettrejustice = 26,
     lettreuniversite = 27,
     pedaleguitare = 10,
     sitehelmet = 14,
     speakersrepared = 15,
}
